<?php
/** 
 * Copyright (c) 2016 simpart
 *  
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * @file   route.php
 * @brief  routing controll function
 * @author simpart
 * @note   generated by trut
 */
namespace route;

/*** require ***/
require_once( __DIR__   . DIRECTORY_SEPARATOR .
              'session' . DIRECTORY_SEPARATOR .
              'crud.php' );
require_once( __DIR__   . DIRECTORY_SEPARATOR .
              'session' . DIRECTORY_SEPARATOR . 
              'route.php' );
require_once( __DIR__ . DIRECTORY_SEPARATOR . 'common.php' );

try {
    $cnt = 0;
    while( true ) {
        /* session routing */
        $grp = \session\getMatchGrp( $cnt );
        if( null === $grp ) {
            /* not match any group */
            break;
        }
        /* url routing */
        require_once( 
            __DIR__ . DIRECTORY_SEPARATOR .
            $grp    . DIRECTORY_SEPARATOR .
            'SgrpCtrl.php'
        );
        $execTgt = '\\'.$grp.'\\'.'execTgt';
        $uri     = getNoprmUri( $_SERVER['REQUEST_URI'] );
        if (true === $execTgt( $uri )) {
            return;
        }
        $cnt++;
    }
    require_once('@gen1');
} catch ( \Exception $e ) {
    throw new \Exception(
        PHP_EOL.'ERR(File:'.basename(__FILE__).',Line:'.__line__.'):'.
        __FUNCTION__.'()'.$e->getMessage()
    );
}
/* end of file */
